theme: jekyll-theme-minimal
title: Dr. Arun Kumar Pandey
description: D.S. Kothari Postdoctoral Fellow at Department of Physics and Astrophysics, University of Delhi
logo: https://drive.google.com/file/d/1wbabuQvZHMKvR2wqg6PMO5OZM4-ZvOo-/view?usp=sharing
show_downloads: false
